### ISSUE TITLE
node-firefox to work on FirefoxOS devices

### ISSUE THREAD

**Issue by arcturus** [mozilla/node-firefox#24] opened 2015-02-09 22:06 UTC
Right now we can just use the simulator if we want to use node-firefox modules, but gaia build system could get better if we can actually perform all this nice actions on real devices :)

**Comment by sole** [comment] 2015-02-10 10:44
Yeah, I'd use that feature too!

@arcturus You did some work on adb+node. Do you think we could use it? My idea was this, you tell me if it could work:

- Using adb.js (supposing it's called like that) we detect a device
- We can then set up port forwarding to localhost:someport
- Once we have this port listening we can use node-firefox-connect

Does it make sense?

**Comment by sole** [comment] 2015-02-10 10:46
Expanding more on this:

- We could have a `find-devices` module, returning the device ids that adb detects
- Then a `set-port-forwarding` or similar module using the device ids found above?

What is cool about this is that *we could push to all the connected devices*!!!

!!!

**Comment by nicola** [comment] 2015-02-10 11:26
I can't find other conversations where I mentioned this, but this summer I attempted to implement that into fxos-ports https://github.com/nicola/fx-ports/pull/3, that is the place where I think it should be with some flags (adb=true)

**Comment by sole** [comment] 2015-03-17 13:45
I made a module for installing an app to all ADB connected devices:
https://github.com/sole/install-to-adb

I am not 100% sure if that module is the right approach as it's very limited (BUT EFFECTIVE!) in what it does: pushing an app to devices.

The issue is that you have to run the port forwarding step before you get to connect to anything, and before you do that you need to enumerate the adb devices. Not sure if we want to hide all this, but am also not sure what would gaia need. Push just an app? @arcturus halp!

**Comment by lmorchard** [comment] 2015-03-17 14:15
I was kind of scratching my head about this over the past week or so, too. But, my problem is that not all adb connected devices are FxOS devices. Some will be, you know, Android devices. This is especially annoying for Cordova, which is meant to work cross-platform. 

I started peeking inside the ADB Helper addon. It seems to speculatively connects to the forwarded port and tries to get the FxOS version from the debugging API. If that fails, then it ignores that device as FxOS. The annoyance with that, though, is that you get the connection permission prompt on every device every time unless you disable it with WebIDE first.

So, `adb devices -l` will list things like this:
```
List of devices attached
ZX1G229PZV             device usb:1D111400 product:shamu model:Nexus_6 device:shamu
3739ced5               device usb:1D111213 product:msm8610 model:Flame device:flame
```
I guess another way to go is to keep a list of device names, but that just seems like a big dumb task.

**Comment by lmorchard** [comment] 2015-03-17 14:25
Oh, hey, so I think [this is how ADB Helper does it](https://github.com/mozilla/adbhelper/blob/master/scanner.js#L114):

```
➜  adbhelper  adb devices -l
List of devices attached
ZX1G229PZV             device usb:1D111400 product:shamu model:Nexus_6 device:shamu
3739ced5               device usb:1D111213 product:msm8610 model:Flame device:flame

➜  adbhelper  adb -s ZX1G229PZV shell 'test -f /system/b2g/b2g; echo $?'
1
➜  adbhelper  adb -s 3739ced5 shell 'test -f /system/b2g/b2g; echo $?'
0
```
That's a fun hack.

**Comment by tofumatt** [comment] 2015-03-17 15:10
Hah, that is awesome.

**Comment by lmorchard** [comment] 2015-03-17 21:56
So, I think I could use a combination of that shell hack to look up device IDs, along with adbkit's [listForwards](https://github.com/CyberAgent/adbkit#clientlistforwardsserial-callback) to discover pre-existing port forwards specifically to FxOS devices. And, wherever a forward hasn't been done, we can make one with adbkit's [forward](https://github.com/CyberAgent/adbkit#clientforwardserial-local-remote-callback).

I think I'll play with that stuff tonight / tomorrow morning.

**Comment by sole** [comment] 2015-03-18 17:26
They do get cleaned up :) seems that adbkit picks them up where they were. Otherwise I would have ran out of ports already on my machine specially when running it with 10 phones!

**Comment by sole** [comment] 2015-03-18 17:27
For documentation we discussed on irc to have a `find-devices` module and a `forward-devices` module. Les is going to look into that.

**Comment by lmorchard** [comment] 2015-03-18 21:28
[node-firefox-find-devices is a thing!](https://github.com/mozilla/node-firefox-find-devices), and also have my first PR in to implement it. Tonight or tomorrow, I tackle foward-devices

**Comment by sole** [comment] 2015-03-26 17:55
and [https://github.com/mozilla/node-firefox-forward-ports](https://github.com/mozilla/node-firefox-forward-ports) is another thing! closing because you can now interact with ADB devices! \o/

**Closed by sole** 2015-03-26 17:55 UTC

**Comment by lmorchard** [comment] 2015-03-26 18:51
:100:
